name: Le Phong Vu
description: unknown
meta_description: "This is first line of description.
This is the second line.
Third line...
Over"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'https://lpvcpp.github.io'
google_analytics: 'UA-84558526-1'
disqus: true 
disqus_shortname: 'lpvcpp-github-io'
github_username: 'lpvcpp'

# Details for the RSS feed generator
url:            'https://lpvcpp.github.io'
author:         'lpvcpp'
authorTwitter:  'motsach_theky'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
